# This is a basic workflow to help you get started with Actions

name: Anti-virus Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  AVscan:
    runs-on: ubuntu-latest
    name: AV scan
    steps:
      - name: Checkout resources to scan
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: AV scan using ClamAV
        uses: djdefi/gitavscan@22
