# This is a basic workflow to help you get started with Actions
name: RMSKIN Packager

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

jobs:
  Build_n_Release:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout this Repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      # Runs a rmskin packager action
      - name: Run Build action
        id: builder
        uses: 2bndy5/rmskin-action@v2

      # upload the output from the `builder` step as workflow artifact
      - name: Archive rmskin file as artifact
        uses: actions/upload-artifact@v6
        if: github.event_name != 'release'
        with:
          name: ${{ steps.builder.outputs.arc_name }}
          path: ${{ github.workspace }}/${{ steps.builder.outputs.arc_name }}

      # Upload the asset
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
          ASSET_PATH: ${{ github.workspace }}/${{ steps.builder.outputs.arc_name }}
        run: >-
          gh release upload ${TAG} "${ASSET_PATH}"
