# This is a basic workflow to help you get started with Actions
name: RMSKIN Packager

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:
    branches: [main]

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      arc-name: ${{ steps.builder.outputs.arc-name }}
    steps:
      # Checkout code
      - name: Checkout this Repo
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      # Runs a rmskin packager action
      - name: Run Build action
        id: builder
        uses: 2bndy5/rmskin-action@v2

      # upload the output from the `builder` step as workflow artifact
      - name: Archive rmskin file as artifact
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.builder.outputs.arc-name }}
          path: ${{ github.workspace }}/${{ steps.builder.outputs.arc-name }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout this Repo
        uses: actions/checkout@v6
        with:
          persist-credentials: true

      # Download the rmskin file artifact from the build job
      - name: Download rmskin artifact
        uses: actions/download-artifact@v7
        with:
          name: ${{ needs.build.outputs.arc-name }}

      # Upload the asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.ref_name }}
          ASSET_PATH: ${{ github.workspace }}/${{ needs.build.outputs.arc-name }}
        run: >-
          gh release create ${TAG}
          "${ASSET_PATH}"
          --generate-notes
          --title "${TAG}"
